apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
data:
  USER_UID: "1000"
  USER_GID: "1000"

  FORGEJO__database__DB_TYPE: postgres
  FORGEJO__database__HOST: $DATABASE_HOST:5432
  FORGEJO__database__NAME: forgejodb
  FORGEJO__database__USER: forgejo

  FORGEJO__server__DOMAIN: forgejo.home.arpa
  FORGEJO__server__ROOT_URL: https://forgejo.home.arpa/
  FORGEJO__server__HTTP_PORT: "3000"

  FORGEJO__server__SSH_DOMAIN: forgejo.home.arpa
  FORGEJO__server__SSH_PORT: "2222"
  FORGEJO__server__SSH_LISTEN_PORT: "2222"
  FORGEJO__server__START_SSH_SERVER: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-secrets
type: Opaque
stringData:
  FORGEJO__database__PASSWD: ${K3S_DB_PASSWORD}
