- name: Uninstall k3s on Controller
  hosts: controller
  gather_facts: yes
  become: yes
  tasks:
    - name: Run k3s uninstall script
      shell: >
        /usr/local/bin/k3s-uninstall.sh
      register: k3s_script_controller
      async: 60 # Timeout de 2 minutos (120 segundos)
      poll: 5 # Verifica o status a cada 10 segundos
    - debug: var=k3s_script_controller.stdout_lines
